### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Zomb1rbro** [MrMeowzz/Funkin-MrMeowzz#46]
Hi
i would like to know how did you make your own html version in github
Respond if you can
Thanks.

**Comment by MrMeowzz** [comment]
Like what exactly about making a html version? Being able to play it or something else?

**Comment by Zomb1rbro** [comment]
Compiling the game and being able to play it

**Comment by MrMeowzz** [comment]
Well I just used github pages to be able to play it and to compile it you just run 'lime test html5 -release'

**Comment by Zomb1rbro** [comment]
k 
I´ll try that

**Comment by Zomb1rbro** [comment]
ok
i compiled the files 
do i just manually put all of the files in github or is there do i have to do somethings else.

**Comment by MrMeowzz** [comment]
Yes

**Comment by Zomb1rbro** [comment]
k

**Comment by Zomb1rbro** [comment]
Whenever i load the game the screen goes black is there something else that i´m doing wrong?

**Comment by MrMeowzz** [comment]
Do you have all of the html files uploaded?

**Comment by Zomb1rbro** [comment]
yes 
the index

**Comment by Zomb1rbro** [comment]
nevermind you were right i missed the txt file

**Comment by MrMeowzz** [comment]
oh

**Comment by Zomb1rbro** [comment]
but the resolution does not fit the whole screen
is there a fix

**Comment by MrMeowzz** [comment]
is resizeable set to true in the project.xml file for html5

**Comment by Zomb1rbro** [comment]
yes
